bind 127.0.0.1
port 56379
protected-mode yes
daemonize no
supervised no
dir /var/lib/pocketdisco/redis
aclfile /etc/pocketdisco/redis.acl
databases 1
maxclients 128
maxmemory 128mb
maxmemory-policy noeviction
timeout 0
tcp-keepalive 60
save ""
appendonly no
loglevel warning
logfile ""
slowlog-log-slower-than -1
latency-monitor-threshold 0
client-query-buffer-limit 1mb
proto-max-bulk-len 1mb
client-output-buffer-limit normal 1mb 512kb 60
client-output-buffer-limit pubsub 2mb 1mb 60
